export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white p-8 max-w-3xl mx-auto">
      <h1 className="text-3xl font-bold mb-6">Terms of Service</h1>
      <p className="text-sm text-gray-500 mb-8">Last updated: February 2026</p>

      <div className="space-y-6 text-gray-700 leading-relaxed">
        <section>
          <h2 className="text-xl font-semibold mb-2">1. Acceptance of Terms</h2>
          <p>By using Eastern Fortune 2026, you agree to these terms. If you do not agree, please do not use the app.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">2. Service Description</h2>
          <p>Eastern Fortune 2026 provides fortune readings based on Saju (Four Pillars of Destiny), an East Asian astrology system. Readings are generated by AI and are for entertainment purposes only.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">3. Payments</h2>
          <p>In-app fortune readings may require payment via Solana blockchain tokens (SOL, USDC, SKR, or POOP). All payments are final and non-refundable due to the nature of blockchain transactions.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">4. Disclaimer</h2>
          <p>Fortune readings are for entertainment purposes only and should not be used as the basis for financial, medical, legal, or other important decisions. We make no guarantees about the accuracy of any fortune reading.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">5. Intellectual Property</h2>
          <p>All content, design, and code in Eastern Fortune 2026 is owned by the developer. You may not copy, modify, or distribute the app without permission.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">6. Limitation of Liability</h2>
          <p>Eastern Fortune 2026 is provided "as is" without warranties. We are not liable for any damages arising from use of the app, including but not limited to financial losses from blockchain transactions.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">7. Contact</h2>
          <p>For questions about these terms, contact us at winmbk99@gmail.com</p>
        </section>
      </div>
    </div>
  );
}
