'use client';

import { useLanguage } from '@/lib/LanguageContext';
import LanguageToggle from '../components/LanguageToggle';

export default function TermsPage() {
  const { language } = useLanguage();
  const isKo = language === 'ko';

  return (
    <div className="min-h-screen bg-white p-8 max-w-3xl mx-auto">
      <LanguageToggle />
      <h1 className="text-3xl font-bold mb-6">{isKo ? '이용약관' : 'Terms of Service'}</h1>
      <p className="text-sm text-gray-500 mb-8">{isKo ? '최종 수정일: 2026년 3월' : 'Last updated: March 2026'}</p>

      <div className="space-y-6 text-gray-700 leading-relaxed">
        <section>
          <h2 className="text-xl font-semibold mb-2">{isKo ? '1. 이용약관 동의' : '1. Acceptance of Terms'}</h2>
          <p>{isKo
            ? 'Eastern Fortune 2026을 이용함으로써 본 약관에 동의하는 것으로 간주됩니다. 동의하지 않으시면 서비스를 이용하지 마세요. 만 13세 이상(EU 지역은 16세 이상)부터 이용 가능합니다.'
            : 'By using Eastern Fortune 2026, you agree to these terms. If you do not agree, please do not use the app. You must be at least 13 years old (16 in EU) to use this service.'}</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">{isKo ? '2. 서비스 설명' : '2. Service Description'}</h2>
          <p>{isKo ? 'Eastern Fortune 2026은 두 가지 시스템으로 운세를 제공합니다:' : 'Eastern Fortune 2026 provides fortune readings based on two systems:'}</p>
          <ul className="list-disc ml-6 mt-2 space-y-1">
            <li><strong>{isKo ? '사주명리 (四柱命理)' : 'Saju (Four Pillars of Destiny)'}</strong> - {isKo ? '연/월/일/시 기반 동양 전통 운세 분석' : 'East Asian astrology analyzing birth year, month, day, and hour'}</li>
            <li><strong>{isKo ? '자미두수 (紫微斗數)' : 'Zi Wei Dou Shu (Purple Star Astrology)'}</strong> - {isKo ? '12궁 성요 배치 기반 중국 전통 운명 분석' : 'Chinese astrology using a 12-palace star chart system'}</li>
          </ul>
          <p className="mt-2">{isKo
            ? '모든 운세 해석은 AI가 생성하며, 오락 목적으로만 제공됩니다.'
            : 'All readings are generated by AI and are for entertainment purposes only.'}</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">{isKo ? '3. 결제' : '3. Payments'}</h2>
          <p>{isKo
            ? '프리미엄 운세 및 자미두수 상세 해석은 솔라나 블록체인 토큰으로 결제해야 합니다:'
            : 'Premium fortune readings and Zi Wei Dou Shu detailed interpretations may require payment via Solana blockchain tokens:'}</p>
          <ul className="list-disc ml-6 mt-2 space-y-1">
            <li><strong>SOL</strong> - 0.005 SOL</li>
            <li><strong>USDC</strong> - 1.00 USDC</li>
            <li><strong>SKR (Seeker)</strong> - 15 SKR</li>
            <li><strong>POOP (Poop Dodge)</strong> - 1000 POOP</li>
          </ul>
          <p className="mt-2">{isKo
            ? '블록체인 거래 특성상 모든 결제는 최종적이며 환불이 불가합니다. 웹 사용자는 전체 운세를 무료로 이용할 수 있습니다.'
            : 'All payments are final and non-refundable due to the nature of blockchain transactions. Web users can access full readings for free.'}</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">{isKo ? '4. POOP 토큰 & Poop Dodge' : '4. POOP Token & Poop Dodge'}</h2>
          <p>{isKo
            ? 'POOP 토큰은 무료 아케이드 게임 '
            : 'POOP tokens can be earned by playing '}<a href="https://poop-dodge-game.vercel.app" className="text-purple-600 underline" target="_blank" rel="noopener noreferrer">Poop Dodge</a>{isKo
            ? '를 플레이하여 획득할 수 있습니다. POOP 토큰은 오락 목적으로만 배포되며 금전적 가치가 보장되지 않습니다. 증권이나 투자 상품이 아닙니다.'
            : ', a free arcade game. POOP tokens are distributed for entertainment purposes only and have no guaranteed monetary value. They are not securities or investment instruments.'}</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">{isKo ? '5. 지갑 보안' : '5. Wallet Security'}</h2>
          <p>{isKo
            ? '솔라나 지갑의 보안은 전적으로 사용자의 책임입니다. 개인키, 시드 구문, 비밀번호를 절대 요구하지 않습니다. 지갑 자격 증명을 안전하게 보관하세요.'
            : 'You are fully responsible for the security of your Solana wallet. We will never ask for your private keys, seed phrase, or passwords. Keep your wallet credentials secure.'}</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">{isKo ? '6. 면책 조항' : '6. Disclaimer'}</h2>
          <p>{isKo
            ? '운세 해석은 오락 목적으로만 제공되며, 재무, 의료, 법률 등 중요한 결정의 근거로 사용해서는 안 됩니다. 사주명리 또는 자미두수 분석의 정확성을 보장하지 않습니다.'
            : 'Fortune readings are for entertainment purposes only and should not be used as the basis for financial, medical, legal, or other important decisions. We make no guarantees about the accuracy of any fortune reading, whether from Saju or Zi Wei Dou Shu analysis.'}</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">{isKo ? '7. 지적재산권' : '7. Intellectual Property'}</h2>
          <p>{isKo
            ? 'Eastern Fortune 2026의 모든 콘텐츠, 디자인, 코드는 개발자에게 귀속됩니다. 허가 없이 앱을 복사, 수정, 배포할 수 없습니다.'
            : 'All content, design, and code in Eastern Fortune 2026 is owned by the developer. You may not copy, modify, or distribute the app without permission.'}</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">{isKo ? '8. 책임 제한' : '8. Limitation of Liability'}</h2>
          <p>{isKo
            ? 'Eastern Fortune 2026은 "있는 그대로" 제공되며 어떠한 보증도 하지 않습니다. 블록체인 거래로 인한 재정적 손실을 포함하여 앱 사용으로 발생하는 어떠한 손해에 대해서도 책임지지 않습니다. 최대 책임 한도는 $10 또는 지난 12개월간 결제 금액 중 적은 금액입니다.'
            : 'Eastern Fortune 2026 is provided "as is" without warranties. We are not liable for any damages arising from use of the app, including but not limited to financial losses from blockchain transactions. Maximum liability is limited to $10 or payments made in the past 12 months, whichever is less.'}</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">{isKo ? '9. 관련 서비스' : '9. Related Services'}</h2>
          <ul className="list-disc ml-6 space-y-1">
            <li><a href="https://poop-dodge-game.vercel.app/privacy" className="text-purple-600 underline" target="_blank" rel="noopener noreferrer">Poop Dodge {isKo ? '개인정보처리방침' : 'Privacy Policy'}</a></li>
            <li><a href="https://poop-dodge-game.vercel.app/terms" className="text-purple-600 underline" target="_blank" rel="noopener noreferrer">Poop Dodge {isKo ? '이용약관' : 'Terms & Conditions'}</a></li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">{isKo ? '10. 문의' : '10. Contact'}</h2>
          <p>{isKo
            ? '이용약관 관련 문의: person.bk.scholarship@gmail.com'
            : 'For questions about these terms, contact us at person.bk.scholarship@gmail.com'}</p>
        </section>
      </div>

      <div className="mt-8 pt-6 border-t border-gray-200 text-center text-sm text-gray-500">
        <a href="/" className="text-purple-600 hover:underline">{isKo ? '← 홈으로' : '← Back to Home'}</a>
      </div>
    </div>
  );
}
